name: Wake up Streamlit

on:
  schedule:
    # Executa a cada 4 horas
    - cron: '0 */4 * * *'
  workflow_dispatch: 

jobs:
  wake_up:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar sinal de despertar
        run: |
          # O '|| true' garante que o GitHub Actions sempre marque como SUCESSO
          curl -A "Mozilla/5.0" --max-time 30 https://presbeamcheck.streamlit.app/ || true